# Generated by Django 5.0.3 on 2024-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('Train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Train_Name', models.CharField(max_length=100)),
                ('start_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField()),
                ('Start_Station_Code', models.CharField(max_length=20)),
                ('End_Station_Code', models.CharField(max_length=20)),
            ],
        ),
    ]
